#!/usr/bin/env bash

if [ "$*" = "󰐥 " ]; then
  command=$"systemctl poweroff"
  # Override the previously set prompt.
  echo -en "\x00prompt\x1fChange prompt\n"
  echo -en "󱎘 \n"
  echo -en "󰄬 \n"
fi

if [ "$*" = "󰑓 " ]; then
  command=$"systemctl reboot"
  # Override the previously set prompt.
  echo -en "\x00prompt\x1fChange prompt\n"
  echo -en "󱎘 ​\n"
  echo -en "󰄬 ​\n"
fi

if [ "$*" = "󰄬 ​" ]; then
  systemctl reboot
  exit 0
fi

if [ "$*" = "󱎘 ​" ]; then
  exit 0
fi

if [ "$*" = "󰄬 " ]; then
  systemctl poweroff
  exit 0
fi

if [ "$*" = "󱎘 " ]; then
  exit 0
fi

if [ "$*" = " " ]; then
  swaylock --fade-in 0.3 --screenshot --clock --datestr %d.%m.%Y --indicator --effect-blur 10x10
  exit 0
fi

if [ "$@" ]; then
  # Override the previously set prompt.
  echo -en "\x00prompt\x1fChange prompt\n"
else
  echo -en " \n"
  echo -en "󰐥 \n"
  echo -en "󰑓 \n"
fi
